version: "3.8"

services:
  db:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: items
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
